apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      initContainers:
        - name: chown
          image: "11notes/k8s-init"
          command:
            - sh
            - -c
            - |
              eleven k8s chown /postgres {{ .Values.containerSecurityContext.runAsUser | default 1000 }} {{ .Values.containerSecurityContext.runAsGroup | default 1000 }}
          volumeMounts:
            - name: etc
              mountPath: /postgres/etc
            - name: var
              mountPath: /postgres/var
          securityContext:
            runAsUser: 0